### ISSUE TITLE
JAVA_HOME is not set

### ISSUE THREAD

**Issue by ghost** [dnafrance/vagrant-hadoop-spark-cluster#3]
When trying to start Spark ($SPARK_HOME/sbin/start-all.sh) I get an error: 

[vagrant@node1 ~]$ sudo $SPARK_HOME/sbin/start-all.sh
starting org.apache.spark.deploy.master.Master, logging to /usr/local/spark-1.1.1-bin-hadoop2.4/sbin/../logs/spark-root-org.apache.spark.deploy.master.Master-1-node1.out
failed to launch org.apache.spark.deploy.master.Master:
  JAVA_HOME is not set

**Comment by dnafrance** [comment]
@tshouri - Ensure you set up your Java environment correctly and exported JAVA_HOME environment variable, if it's not in your path.
